import type { Character } from '../types/character'
import { MONK_FEATURES } from './monkFeatures'

export const CHARACTER_SEED: Character = {
  id: 'thu-c',
  name: "Vrchní Šišník Thu'C",
  race: 'Dragonborn (Bronze)',
  background: 'Soldier',
  alignment: 'Chaotic Neutral',
  classes: [{ name: 'Monk', level: 7 }],

  abilityScores: {
    str: 12,
    dex: 18,
    con: 17,
    int: 12,
    wis: 16,
    cha: 8,
  },
  proficiencyBonus: 3,
  inspiration: false,

  armorClass: 17,
  speed: 45,
  hitPoints: {
    current: 59,
    max: 59,
    temp: 0,
  },
  hitDiceRemaining: 7,
  hitDiceTotal: 7,
  hitDiceType: 8,

  deathSaves: {
    successes: 0,
    failures: 0,
  },

  focusPoints: {
    current: 7,
    max: 7,
  },

  attacks: [
    {
      id: 'unarmed-1',
      name: 'Unarmed Strike',
      attackBonus: 'dex',
      flatBonus: 0,
      proficient: true,
      damageDice: '1d8',
      damageAbility: 'dex',
      damageType: 'bludgeoning',
      isMartialArts: true,
      isBonusAction: false,
      fpCost: 0,
      notes: 'Martial Arts die (max of weapon or 1d8)',
    },
    {
      id: 'unarmed-2',
      name: 'Unarmed Strike (Extra)',
      attackBonus: 'dex',
      flatBonus: 0,
      proficient: true,
      damageDice: '1d8',
      damageAbility: 'dex',
      damageType: 'bludgeoning',
      isMartialArts: true,
      isBonusAction: false,
      fpCost: 0,
      notes: 'Extra Attack',
    },
    {
      id: 'flurry',
      name: 'Flurry of Blows',
      attackBonus: 'dex',
      flatBonus: 0,
      proficient: true,
      damageDice: '1d8',
      damageAbility: 'dex',
      damageType: 'bludgeoning',
      isMartialArts: true,
      isBonusAction: true,
      fpCost: 1,
      notes: '1 FP – Bonus Action – 2 unarmed strikes. Then choose Open Hand effect.',
    },
    {
      id: 'beampal',
      name: 'Beampal (Laser Pistol +1)',
      attackBonus: 'dex',
      flatBonus: 1,
      proficient: true,
      damageDice: '2d6',
      damageAbility: 'dex',
      damageType: 'force',
      isMartialArts: false,
      isBonusAction: false,
      fpCost: 0,
      notes: 'Firearm, magic +1. Monk weapon. Range (40/120). Properties: Reload, Vex.',
    },
    {
      id: 'starry-wisp',
      name: 'Starry Wisp (Star Map)',
      attackBonus: 'flat',
      flatBonus: 5,
      proficient: false,
      damageDice: '0',
      damageAbility: 'none',
      damageType: 'radiant',
      isMartialArts: false,
      isBonusAction: false,
      fpCost: 0,
      notes: 'Star Map cantrip (Sickle constellation). Range 60 ft. Target begins to glow: cannot be made invisible and attacks against it have no disadvantage from darkness until start of your next turn.',
    },
    {
      id: 'blade-ward',
      name: 'Blade Ward (Star Map)',
      attackBonus: 'flat',
      flatBonus: 0,
      proficient: false,
      damageDice: '0',
      damageAbility: 'none',
      damageType: 'bludgeoning',
      isMartialArts: false,
      isBonusAction: false,
      fpCost: 0,
      notes: 'Star Map cantrip (Defender constellation). DC 13 DEX save. Grants resistance to Bludgeoning, Piercing, and Slashing damage until end of next turn.',
    },
  ],

  savingThrowProficiencies: {
    str: true,
    dex: true,
    con: false,
    int: false,
    wis: false,
    cha: false,
  },

  skillProficiencies: {
    acrobatics: { proficient: true, expertise: false },
    'animal-handling': { proficient: false, expertise: false },
    arcana: { proficient: false, expertise: false },
    athletics: { proficient: true, expertise: false },
    deception: { proficient: false, expertise: false },
    history: { proficient: false, expertise: false },
    insight: { proficient: false, expertise: false },
    intimidation: { proficient: true, expertise: false },
    investigation: { proficient: false, expertise: false },
    medicine: { proficient: false, expertise: false },
    nature: { proficient: false, expertise: false },
    perception: { proficient: true, expertise: false },
    performance: { proficient: false, expertise: false },
    persuasion: { proficient: false, expertise: false },
    religion: { proficient: false, expertise: false },
    'sleight-of-hand': { proficient: false, expertise: false },
    stealth: { proficient: false, expertise: false },
    survival: { proficient: false, expertise: false },
  },

  classFeatures: MONK_FEATURES,

  inventory: [
    { id: 'laser-pistol', name: 'Laser Pistol +1', quantity: 1, weight: 2, equipped: true, notes: 'Beampal – 2d6 Force, magic +1. Monk weapon. Range (40/120). Properties: Firearms, Reload, Vex.', isMagic: true },
    { id: 'potion-healing', name: 'Potion of Healing', quantity: 1, weight: 0.5, equipped: false, notes: '2d4+2 HP', isMagic: true },
    { id: 'quarterstaff', name: 'Quarterstaff', quantity: 1, weight: 4, equipped: false, notes: 'Monk weapon. Versatile (1d8). Property: Topple.', isMagic: false },
    { id: 'butcher-knife', name: 'Butcher Knife', quantity: 1, weight: null, equipped: true, notes: '', isMagic: false },
    { id: 'seasoning-herbs', name: 'Seasoning Herbs', quantity: 1, weight: null, equipped: false, notes: '', isMagic: false },
    { id: 'firespice', name: 'Firespice', quantity: 14, weight: null, equipped: false, notes: 'Deals fire damage (CON save). Advantage on Intimidation checks. Minimum damage roll (tbc).', isMagic: false },
    { id: 'star-map', name: 'Star Map', quantity: 1, weight: null, equipped: false, notes: 'Parchment with centaur constellations. +1d10 on Survival checks (navigating by stars). After Long Rest: choose one constellation → cantrip (+5 to hit, DC 13): Defender=Blade Ward, Falcon=Light, Tamarisk=Goodberry, Sickle=Starry Wisp.', isMagic: true },
    { id: 'bonefire-charm', name: 'Bonefire Charm', quantity: 1, weight: null, equipped: false, notes: '4-inch fiery glass sculpture with a magical ember. When placed on a burning campfire or torch: friendly creatures within the fire\'s light who spend Hit Dice during a Short Rest treat a roll of 1 as a 2.', isMagic: true },
    { id: 'trpaslic-koyeni', name: 'Trpasličí koření', quantity: 1, weight: null, equipped: false, notes: 'Konzervant na potraviny (food preservative).', isMagic: false },
    { id: 'iron-pot', name: 'Iron Pot', quantity: 1, weight: 10, equipped: false, notes: '', isMagic: false },
    { id: 'rope', name: 'Rope', quantity: 1, weight: 5, equipped: false, notes: '50 ft', isMagic: false },
    { id: 'torch', name: 'Torch', quantity: 1, weight: 1, equipped: false, notes: '', isMagic: false },
    { id: 'dice', name: 'Dice', quantity: 1, weight: null, equipped: false, notes: '', isMagic: false },
    { id: 'healers-kit', name: "Healer's Kit", quantity: 1, weight: 3, equipped: false, notes: '', isMagic: false },
    { id: 'travelers-clothes', name: "Traveler's Clothes", quantity: 1, weight: 4, equipped: true, notes: '', isMagic: false },
  ],
  gold: 826,

  spellcastingAbility: null,
  spellSlots: [],
  spells: [],

  resistances: ['lightning'],
  languages: ['Common', 'Draconic', 'Orc'],
  proficienciesWeapons: ['Crossbow', 'Hand Firearms', 'Scimitar', 'Shortsword', 'Simple Weapons'],
  proficienciesTools: ["Cook's Utensils", 'Dragonchess Set'],

  darkvision: 60,

  personalityTraits: 'Picky, cunning, pragmatical, short fuse',
  ideals: 'There is nothing more important than a good food',
  bonds: 'His Beampal',
  flaws: 'Temperous',
  appearance: "For people who didn't meet much draconics, looks like another draconic. For other draconics, looks weird and a little retarded.",
  eyes: 'Yellow',
  hair: 'Colorfull feathers',
  skin: 'Brass with rainbow undertones',

  updatedAt: Date.now(),
}
